/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.Main.WorkSpaceProfiles;

import MarketAnalytics.AnalysisHelper;
import TheBusiness.Business.Business;
import TheBusiness.SalesManagement.SalesPersonProfile;
import UserInterface.ManageTheBusiness.ManageChannelsJPanel;
import UserInterface.ManageTheBusiness.ManageMarketsJPanel;
import UserInterface.ManageTheBusiness.ManagePricesJPanel;
import UserInterface.ManageTheBusiness.PerformaceReportMarketingJPanel;
import UserInterface.ProductManagement.ManagePriceJPanel;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class MarketingManagerWorkAreaJPanel1 extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    AnalysisHelper helper;
    SalesPersonProfile salesperson;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public MarketingManagerWorkAreaJPanel1(Business b, JPanel clp) {

        this.business = b;
        this.CardSequencePanel = clp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageMarket = new javax.swing.JButton();
        btnManageChannels = new javax.swing.JButton();
        btnManagePrices = new javax.swing.JButton();
        btnPerformanceReports = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnManageMarket.setBackground(new java.awt.Color(102, 153, 255));
        btnManageMarket.setFont(getFont());
        btnManageMarket.setForeground(new java.awt.Color(255, 255, 255));
        btnManageMarket.setText("Manage Markets");
        btnManageMarket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageMarket.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageMarket.setMinimumSize(new java.awt.Dimension(20, 23));
        btnManageMarket.setPreferredSize(new java.awt.Dimension(240, 30));
        btnManageMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageChannels.setBackground(new java.awt.Color(102, 153, 255));
        btnManageChannels.setFont(getFont());
        btnManageChannels.setForeground(new java.awt.Color(255, 255, 255));
        btnManageChannels.setText("Manage Channels");
        btnManageChannels.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageChannels.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageChannels.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageChannels.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageChannels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageChannelsActionPerformed(evt);
            }
        });

        btnManagePrices.setBackground(new java.awt.Color(102, 153, 255));
        btnManagePrices.setFont(getFont());
        btnManagePrices.setForeground(new java.awt.Color(255, 255, 255));
        btnManagePrices.setText("Manage Prices");
        btnManagePrices.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManagePrices.setMaximumSize(new java.awt.Dimension(145, 40));
        btnManagePrices.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManagePrices.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManagePrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePricesIdentifyEventsActionPerformed(evt);
            }
        });

        btnPerformanceReports.setBackground(new java.awt.Color(102, 153, 255));
        btnPerformanceReports.setFont(getFont());
        btnPerformanceReports.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformanceReports.setText("Performance Reports");
        btnPerformanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerformanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerformanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerformanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManageMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnManageChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManagePrices, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(418, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManagePrices, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageMarketIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();

        ManageMarketsJPanel manageMarket = new ManageMarketsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageMarketPanel", manageMarket);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnManageMarketIdentifyResourceAssetsActionPerformed

    private void btnManageChannelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageChannelsActionPerformed
        // TODO add your handling code here:

        ManageChannelsJPanel manageChannels = new ManageChannelsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageChannelPanel", manageChannels);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnManageChannelsActionPerformed

    private void btnManagePricesIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePricesIdentifyEventsActionPerformed
        // TODO add your handling code here:
        
          ManagePricesJPanel managePrice = new ManagePricesJPanel(business, CardSequencePanel, helper);

        CardSequencePanel.add("ManagePricePanel", managePrice);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

}//GEN-LAST:event_btnManagePricesIdentifyEventsActionPerformed

    private void btnPerformanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportsActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        AnalysisHelper helper = new AnalysisHelper();
        PerformaceReportMarketingJPanel performanceReport = new PerformaceReportMarketingJPanel(business, CardSequencePanel,helper,salesperson);

        CardSequencePanel.add("PerformanceReportMarketingPanel", performanceReport);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_btnPerformanceReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageChannels;
    private javax.swing.JButton btnManageMarket;
    private javax.swing.JButton btnManagePrices;
    private javax.swing.JButton btnPerformanceReports;
    // End of variables declaration//GEN-END:variables

}
