/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.Main.WorkSpaceProfiles;

import MarketAnalytics.AnalysisHelper;
import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerProfile;
import TheBusiness.SalesManagement.SalesPersonProfile;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.CheckOrderStatus;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.ManageProfileJPanel;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.ManageSalesPersonOrders;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.PerformanceReportsJPanel;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.ProcessOrder;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.ReviewCommisionJPanel;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class SalesPersonWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    SalesPersonProfile salesperson;
    AnalysisHelper helper;

    /**
     * Creates new form UnitRiskWorkArea
     * @param b
     * @param spp
     * @param clp
     */

    public SalesPersonWorkAreaJPanel(Business b, SalesPersonProfile spp, JPanel clp) {

        this.business = b;
        this.CardSequencePanel = clp;
        salesperson = spp;
        initComponents();

    }

    public SalesPersonWorkAreaJPanel(Business b, JPanel cp) {
        this.business=b;
        this.CardSequencePanel=cp;
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnServeCustomer = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        btnReviewOrder = new javax.swing.JButton();
        btnReviewComission = new javax.swing.JButton();
        btnPerformanceReports = new javax.swing.JButton();
        btnOrderStatus = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnServeCustomer.setBackground(new java.awt.Color(102, 153, 255));
        btnServeCustomer.setFont(getFont());
        btnServeCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnServeCustomer.setText("Serve Customers");
        btnServeCustomer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnServeCustomer.setMaximumSize(new java.awt.Dimension(200, 40));
        btnServeCustomer.setMinimumSize(new java.awt.Dimension(20, 23));
        btnServeCustomer.setPreferredSize(new java.awt.Dimension(240, 30));
        btnServeCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServeCustomerIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnManageProfile.setFont(getFont());
        btnManageProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnManageProfile.setText("Manage Profile");
        btnManageProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageProfile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        btnReviewOrder.setBackground(new java.awt.Color(102, 153, 255));
        btnReviewOrder.setFont(getFont());
        btnReviewOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnReviewOrder.setText("Review Order Status History");
        btnReviewOrder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReviewOrder.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReviewOrder.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReviewOrder.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReviewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewOrderActionPerformed(evt);
            }
        });

        btnReviewComission.setBackground(new java.awt.Color(102, 153, 255));
        btnReviewComission.setFont(getFont());
        btnReviewComission.setForeground(new java.awt.Color(255, 255, 255));
        btnReviewComission.setText("Review Comission");
        btnReviewComission.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReviewComission.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReviewComission.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReviewComission.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReviewComission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewComissionActionPerformed(evt);
            }
        });

        btnPerformanceReports.setBackground(new java.awt.Color(102, 153, 255));
        btnPerformanceReports.setFont(getFont());
        btnPerformanceReports.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformanceReports.setText("Performance Reports");
        btnPerformanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerformanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerformanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerformanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportsActionPerformed(evt);
            }
        });

        btnOrderStatus.setBackground(new java.awt.Color(102, 153, 255));
        btnOrderStatus.setFont(getFont());
        btnOrderStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderStatus.setText("Check Order Status");
        btnOrderStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrderStatus.setMaximumSize(new java.awt.Dimension(200, 40));
        btnOrderStatus.setMinimumSize(new java.awt.Dimension(20, 20));
        btnOrderStatus.setPreferredSize(new java.awt.Dimension(240, 25));
        btnOrderStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnServeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReviewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReviewComission, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReviewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReviewComission, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(310, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnServeCustomerIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServeCustomerIdentifyResourceAssetsActionPerformed
        
// TODO add your handling code here:

// 
//        String customername = customerNameTextField.getText();
//        if (customername.isEmpty()) return;
//        CustomerProfile selectedcustomer = business.getCustomerDirectory().findCustomer(customername);

        ProcessOrder aos = new ProcessOrder(business,salesperson, CardSequencePanel);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnServeCustomerIdentifyResourceAssetsActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        // TODO add your handling code here:
        ManageProfileJPanel manageProfile=new ManageProfileJPanel(business,CardSequencePanel,salesperson);
        CardSequencePanel.add("ManageProfileJPanel",manageProfile);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

}//GEN-LAST:event_btnManageProfileActionPerformed

    private void btnReviewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewOrderActionPerformed
        // TODO add your handling code here:

        ManageSalesPersonOrders iet = new ManageSalesPersonOrders(business, salesperson, CardSequencePanel);

        CardSequencePanel.add("FindResourceAsset", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnReviewOrderActionPerformed

    private void btnReviewComissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewComissionActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
        ReviewCommisionJPanel reviewPanel=new ReviewCommisionJPanel(business,CardSequencePanel,salesperson);
        CardSequencePanel.add("ReviewCommisionJPanel",reviewPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_btnReviewComissionActionPerformed

    private void btnPerformanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportsActionPerformed
        // TODO add your handling code here:

        CardSequencePanel.removeAll();
                AnalysisHelper helper = new AnalysisHelper();

         PerformanceReportsJPanel performanceReport=new PerformanceReportsJPanel(business,CardSequencePanel,helper,salesperson);
         CardSequencePanel.add("PerformanceReportsJPanel",performanceReport);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_btnPerformanceReportsActionPerformed

    private void btnOrderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderStatusActionPerformed
    CheckOrderStatus checkOrderStatusPanel = new CheckOrderStatus(business,CardSequencePanel,salesperson);

    // Add the panel to the CardSequencePanel
    CardSequencePanel.add("CheckOrderStatus", checkOrderStatusPanel);

    // Switch to the CheckOrderStatus panel
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);    }//GEN-LAST:event_btnOrderStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnOrderStatus;
    private javax.swing.JButton btnPerformanceReports;
    private javax.swing.JButton btnReviewComission;
    private javax.swing.JButton btnReviewOrder;
    private javax.swing.JButton btnServeCustomer;
    // End of variables declaration//GEN-END:variables

}
