/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.CertificationAuthorityWorkArea;

import Business.Business;
import Business.UserAccount;
import DegreeRequest.DegreeRequest;
import Professor.Professor;
import UI.SystemAdmin.ViewProfessor;
import UI.main.MainJFrame;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renuka
 */
public class CertificationAuthorityJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CertificationAuthorityJFrame
     */
    Business business;
    UserAccount useraccount ;
    DefaultTableModel tableModel;
    public CertificationAuthorityJFrame() {
        initComponents();
    }
    public CertificationAuthorityJFrame(Business business,UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.useraccount = useraccount;
        this.tableModel = (DefaultTableModel) tblCertificateAuthority.getModel() ;
        populateTable() ;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblCertificationAuthority = new javax.swing.JLabel();
        lblListofRequirements = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCertificateAuthority = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 162, 162));

        btnLogout.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(30, 76, 216));
        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblCertificationAuthority.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        lblCertificationAuthority.setForeground(new java.awt.Color(30, 76, 216));
        lblCertificationAuthority.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCertificationAuthority.setText("Certification Authority Details");

        lblListofRequirements.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblListofRequirements.setText("List of Requests from Students :");

        tblCertificateAuthority.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student Id", "Degree Name", "Degree Requirement", "Students total credits ", "Students GPA", "Request Status"
            }
        ));
        jScrollPane1.setViewportView(tblCertificateAuthority);

        btnApprove.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(30, 76, 216));
        btnApprove.setText("APPROVE");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        btnReject.setForeground(new java.awt.Color(30, 76, 216));
        btnReject.setText("REJECT");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListofRequirements)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnApprove)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReject))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblCertificationAuthority, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(306, 306, 306))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblCertificationAuthority)
                .addGap(70, 70, 70)
                .addComponent(lblListofRequirements)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnReject))
                .addGap(41, 41, 41)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void populateTable() {

    // Clear the existing data in the table
    tableModel.setRowCount(0);

    // Replace 'getDegreeApprovalRequests' with the actual method to get degree approval requests
    List<DegreeRequest> degreeApprovalRequests = business.getCertificationAuthorityDirectory().getDegreeApprovalRequests();

    for (DegreeRequest request : degreeApprovalRequests) {
        Object[] row = new Object[6]; // Assuming you want to display various details

        // Populate the row with data from the DegreeRequest
        row[0] = request.getStudent().getId();
        row[1] = request.getDegree().getName();
        row[2] = request.getDegree().getCreditRequirement();
        row[3] = request.getStudent().getTotalCreditsCompleted();
        row[4] = request.getStudent().getGpa();
        row[5] = request.getStatus();

        tableModel.addRow(row);
    }
}

    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new MainJFrame(this.business, this.useraccount);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCertificateAuthority.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select student to Approve  ","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
         DegreeRequest c = (DegreeRequest) tableModel.getValueAt(selectedRow, 0) ;
         c.setStatus("Approved");
         populateTable() ;
        }
        
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        
         
        int selectedRow = tblCertificateAuthority.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select student to Reject ","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
         DegreeRequest c = (DegreeRequest) tableModel.getValueAt(selectedRow, 0) ;
         c.setStatus("Rejected");
         populateTable() ;
        }
         
    }//GEN-LAST:event_btnRejectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CertificationAuthorityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CertificationAuthorityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CertificationAuthorityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CertificationAuthorityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CertificationAuthorityJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCertificationAuthority;
    private javax.swing.JLabel lblListofRequirements;
    private javax.swing.JTable tblCertificateAuthority;
    // End of variables declaration//GEN-END:variables
}
