/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.StudentWorkArea;

import Business.Business;
import Business.UserAccount;
import CourseOffer.CourseOffer;
import Degree.Degree;
import Professor.Professor;
import Student.Course;
import Student.Student;
import Student.StudentCourseLoad;
import UI.main.MainJFrame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renuka
 */
public class PayCourseFeeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PayCourseFeeJFrame
     */
    Business business;
    UserAccount useraccount;
    Student student;
    public PayCourseFeeJFrame() {
        initComponents();
        this.setVisible(true);
    }
     public PayCourseFeeJFrame(Business business,UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.useraccount = useraccount;
        populateTable();
        
    }
    private void populateTable() {
    DefaultTableModel tableModel = (DefaultTableModel) tblCourse.getModel();
    tableModel.setRowCount(0);  // Clear the existing data in the table

    if (student != null) {
        List<StudentCourseLoad> courseLoadList = student.getStudentCourseLoadDirectory().getCourseLoadList();

        for (StudentCourseLoad courseLoad : courseLoadList) {
            CourseOffer courseOffer = courseLoad.getCourseOffer();
            Course course = courseOffer.getCourse();
            
            if (course != null) {
                String feeStatus = courseLoad.getIsFeePaid() ? "Paid" : "Not Paid";
                
                ArrayList<Professor> professors = course.getProfessorList();
                for (Professor professor : professors) {
                    Object[] row = new Object[]{
                        course.getId(),
                        course.getName(),
                        professor.getId(),    // Assuming Professor class has getId()
                        professor.getName(),  // Assuming Professor class has getName()
                        professor.getReputationIndex(), // Replace with actual method to get reputation if different
                        course.getCredits(),
                        // Price information would need to be retrieved or calculated if available
                        feeStatus
                    };

                    tableModel.addRow(row);
                }
            }
        }
    }
    
    tblCourse.revalidate();
    tblCourse.repaint();
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPayCourseFee = new javax.swing.JLabel();
        lblRegisteredCourses = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblSelectCourse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 164, 164));

        lblPayCourseFee.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        lblPayCourseFee.setForeground(new java.awt.Color(32, 79, 219));
        lblPayCourseFee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPayCourseFee.setText("PAY COURSE FEE");

        lblRegisteredCourses.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblRegisteredCourses.setText("Registered Courses :");

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Course Id", "Course Name", "Professor Id", "Professor Name", "Reputation Index", "Credits", "Price", "Fee Paid Status"
            }
        ));
        jScrollPane2.setViewportView(tblCourse);

        jButton1.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        jButton1.setText("Pay fees to selected course");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnBack.setText("<< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblSelectCourse.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblSelectCourse.setText("Select Course");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPayCourseFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(281, 281, 281))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(btnLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(181, 181, 181))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegisteredCourses)
                    .addComponent(lblSelectCourse))
                .addGap(597, 597, 597))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblPayCourseFee)
                .addGap(57, 57, 57)
                .addComponent(lblRegisteredCourses)
                .addGap(18, 18, 18)
                .addComponent(lblSelectCourse)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut)
                    .addComponent(btnBack))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
          new MainJFrame(this.business, this.useraccount);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          new StudentJFrame(business, useraccount);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    int selectedRow = tblCourse.getSelectedRow();

    if (selectedRow == -1) {
        // No course is selected, show an error message or prompt the user to select a course
        JOptionPane.showMessageDialog(this, "Please select a course to pay fees.", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        
        tblCourse.setValueAt("Paid", selectedRow, tblCourse.getColumn("Fee Paid Status").getModelIndex());
        JOptionPane.showMessageDialog(this, "Course fees paid successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayCourseFeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayCourseFeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayCourseFeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayCourseFeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayCourseFeeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPayCourseFee;
    private javax.swing.JLabel lblRegisteredCourses;
    private javax.swing.JLabel lblSelectCourse;
    private javax.swing.JTable tblCourse;
    // End of variables declaration//GEN-END:variables
}
