/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.StudentWorkArea;

import Business.Business;
import Business.UserAccount;
import UI.main.MainJFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renuka
 */
public class StudentDegreeApprovalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentDegreeApprovalJFrame
     */
    Business business;
    UserAccount useraccount;
    DefaultTableModel table1;
    DefaultTableModel table2;
    public StudentDegreeApprovalJFrame() {
        initComponents();
        this.setVisible(true);
        
    }

     public StudentDegreeApprovalJFrame(Business business,UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.useraccount = useraccount;
        this.table1 = (DefaultTableModel) tblAuthority.getModel() ;
        this.table2 = (DefaultTableModel) tblDegreeApproval.getModel() ;
        populateTable1();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblRequestForDegreeApproval = new javax.swing.JLabel();
        lblCertifyingAuthority = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAuthority = new javax.swing.JTable();
        btnRequest = new javax.swing.JButton();
        lblDegreeAprroved = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDegreeApproval = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 164, 164));

        btnBack.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnBack.setText("<< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblRequestForDegreeApproval.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        lblRequestForDegreeApproval.setForeground(new java.awt.Color(32, 79, 219));
        lblRequestForDegreeApproval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequestForDegreeApproval.setText("Request For Degree Approval from Certifying Authority");

        lblCertifyingAuthority.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblCertifyingAuthority.setText("Certifying Authority :");

        tblAuthority.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Authority Name"
            }
        ));
        jScrollPane1.setViewportView(tblAuthority);

        btnRequest.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnRequest.setText("REQUEST");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        lblDegreeAprroved.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblDegreeAprroved.setText("Degree Approved By");

        tblDegreeApproval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Authority Name"
            }
        ));
        jScrollPane2.setViewportView(tblDegreeApproval);

        btnLogout.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRequestForDegreeApproval, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(btnRequest))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCertifyingAuthority)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDegreeAprroved)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(177, 177, 177))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblRequestForDegreeApproval)
                .addGap(50, 50, 50)
                .addComponent(lblCertifyingAuthority)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRequest)
                .addGap(31, 31, 31)
                .addComponent(lblDegreeAprroved)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnBack))
                .addGap(169, 169, 169))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void populateTable1()
    {
      this.table1.setRowCount(0);
      
      for(CertificationAuthority.CertificationAuthority c: this.business.getCertificationAuthorityDirectory().getList())
      {
        Object row[] = new Object[1] ;
        row[0] = c.getName();
        this.table1.addRow(row); // Add the row to the table model
      }
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          new StudentJFrame(business, useraccount);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAuthority.getSelectedRow();
    
    if (selectedRow == 1) {
        // No row selected, display an error message or take appropriate action.
        JOptionPane.showMessageDialog(this, "Please select a certifying authority to request degree approval from.");
    } else {
        // Get the selected authority's name from the table
        String authorityName = (String) tblAuthority.getValueAt(selectedRow, 0);

        // Here, you can implement the logic to send a request for degree approval
        // to the selected certifying authority. You might show a confirmation
        // message or perform other actions as needed.

        // For example, you can display a confirmation message:
        JOptionPane.showMessageDialog(this, "Request sent to " + authorityName + " for degree approval.");
    }
    
        
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
          new MainJFrame(this.business, this.useraccount);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDegreeApprovalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDegreeApprovalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDegreeApprovalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDegreeApprovalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDegreeApprovalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRequest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCertifyingAuthority;
    private javax.swing.JLabel lblDegreeAprroved;
    private javax.swing.JLabel lblRequestForDegreeApproval;
    private javax.swing.JTable tblAuthority;
    private javax.swing.JTable tblDegreeApproval;
    // End of variables declaration//GEN-END:variables
}
