/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ProfessorWorkArea;

import Business.Business;
import Business.UserAccount;
import CourseOffer.CourseOffer;
import Professor.Professor;
import UI.main.MainJFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renuka
 */
public class ProfessorJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfessorJFrame
     */
      Business business;
    UserAccount useraccount;
    DefaultTableModel professorCourseTable;
    public ProfessorJFrame() {
        initComponents();
    }

     public ProfessorJFrame(Business business,UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.useraccount = useraccount;
        this.professorCourseTable = (DefaultTableModel) profCourseTable.getModel();
        populate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblReputationIndex = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSubscription = new javax.swing.JLabel();
        btnPaySubscription = new javax.swing.JButton();
        lblCourseOffered = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        profCourseTable = new javax.swing.JTable();
        btnAddCourse = new javax.swing.JButton();
        btnUpdateCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        btnEnrolledStudent = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtReputationIndex = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSubscriptionFee = new javax.swing.JTextField();
        btnFeedback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 162, 162));
        jPanel1.setForeground(new java.awt.Color(30, 76, 216));

        lblTitle.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(30, 76, 216));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("PROFESSOR DETAILS");

        lblId.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(30, 76, 216));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("ID :");

        lblName.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(30, 76, 216));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name :");

        lblReputationIndex.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblReputationIndex.setForeground(new java.awt.Color(30, 76, 216));
        lblReputationIndex.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReputationIndex.setText("Reputation Index :");

        lblEmail.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(30, 76, 216));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email :");

        lblSubscription.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblSubscription.setForeground(new java.awt.Color(30, 76, 216));
        lblSubscription.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubscription.setText("Subscription Paid :");

        btnPaySubscription.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnPaySubscription.setText("Pay Subscription Fee");
        btnPaySubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaySubscriptionActionPerformed(evt);
            }
        });

        lblCourseOffered.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCourseOffered.setText("Courses Offered :");

        profCourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Id", "Price", "Duration", "Credits"
            }
        ));
        scrollPane.setViewportView(profCourseTable);

        btnAddCourse.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        btnUpdateCourse.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnUpdateCourse.setText("Update Course");
        btnUpdateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCourseActionPerformed(evt);
            }
        });

        btnDeleteCourse.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnDeleteCourse.setText("Delete Course");
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        btnEnrolledStudent.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnEnrolledStudent.setText("Enrolled Student");
        btnEnrolledStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrolledStudentActionPerformed(evt);
            }
        });

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtSubscriptionFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubscriptionFeeActionPerformed(evt);
            }
        });

        btnFeedback.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnFeedback.setText("Show Feedback");
        btnFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblCourseOffered))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAddCourse)
                            .addGap(39, 39, 39)
                            .addComponent(btnUpdateCourse)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteCourse)
                            .addGap(39, 39, 39)
                            .addComponent(btnEnrolledStudent))
                        .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 155, Short.MAX_VALUE))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPaySubscription)
                .addGap(307, 307, 307))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSubscription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReputationIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSubscriptionFee, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtEmail)
                            .addComponent(txtReputationIndex)
                            .addComponent(txtName)
                            .addComponent(txtId)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(btnLogout)))
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(btnFeedback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReputationIndex)
                    .addComponent(txtReputationIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubscription)
                    .addComponent(txtSubscriptionFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPaySubscription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCourseOffered)
                .addGap(26, 26, 26)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCourse)
                    .addComponent(btnUpdateCourse)
                    .addComponent(btnDeleteCourse)
                    .addComponent(btnEnrolledStudent))
                .addGap(26, 26, 26)
                .addComponent(btnFeedback)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(119, 119, 119))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaySubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaySubscriptionActionPerformed
        // TODO add your handling code here:
        Professor p = this.business.getProfessorDirectory().findByUserName(useraccount.getUsername());
        new SubscriptionFeesJFrame(this.business, this.useraccount, p);
    }//GEN-LAST:event_btnPaySubscriptionActionPerformed

    public void populate(){
        
       
    Professor p = this.business.getProfessorDirectory().findByUserName(useraccount.getUsername());

    if (p != null) {
        // Professor object is not null, you can access its properties safely
        txtId.setText(p.getId());
        txtName.setText(p.getName());
        txtReputationIndex.setText(String.valueOf(p.getReputationIndex()));
        txtEmail.setText(p.getEmail());
        txtSubscriptionFee.setText(String.valueOf(p.isFeesPaid()));
        
        professorCourseTable.setRowCount(0);

        for (CourseOffer b : p.getProfessorCourseOfferDir().getCourseOfferList()) {
            Object row[] = new Object[5];
            row[0] = b;
            row[1] = b.getPrice();
            row[2] = b.getCourse().getDuration();
            row[3] = b.getCourse().getCredits();
            row[4] = b.getTime();

            professorCourseTable.addRow(row);
        }
    } else {
        // Handle the case when the Professor object is null
        // For example, you can display an error message or clear the fields.
        txtName.setText("");  // Clear the name field
        txtReputationIndex.setText("");  // Clear the reputation index field
        txtEmail.setText("");  // Clear the email field
        txtSubscriptionFee.setText("");  // Clear the subscription fee field
        professorCourseTable.setRowCount(0);  // Clear the course table
        // You can also display an error message, e.g., JOptionPane.showMessageDialog.
        // JOptionPane.showMessageDialog(this, "Professor not found", "Error", JOptionPane.ERROR_MESSAGE);
    }


    
    }
    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
      new AddCourses(this.business, this.useraccount);
      this.setVisible(false);
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnUpdateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCourseActionPerformed
        // TODO add your handling code here:
        int selectedRow = profCourseTable.getSelectedRow();

    if (selectedRow == -1) {
        // No course is selected, show an error message or prompt the user to select a course
        JOptionPane.showMessageDialog(this, "Please select a course to update.", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        // Get the selected course from the table
        CourseOffer selectedCourse = (CourseOffer) profCourseTable.getValueAt(selectedRow, 0);
        Professor p = this.business.getProfessorDirectory().findByUserName(useraccount.getUsername());
        new UpdateCourseJFrame(this.business,this.useraccount,p,selectedCourse);
        this.setVisible(false);

    }
    
    }//GEN-LAST:event_btnUpdateCourseActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        // TODO add your handling code here:
          int selectedRow = profCourseTable.getSelectedRow();

    if (selectedRow == -1) {
        // No course is selected, show an error message or prompt the user to select a course
        JOptionPane.showMessageDialog(this, "Please select a course to delete.", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        // Get the selected course from the table
        CourseOffer selectedCourse = (CourseOffer) profCourseTable.getValueAt(selectedRow, 0);
        Professor p = this.business.getProfessorDirectory().findByUserName(useraccount.getUsername());
        p.getProfessorCourseOfferDir().getCourseOfferList().remove(selectedCourse);
        professorCourseTable.removeRow(selectedRow);
        JOptionPane.showMessageDialog(this, "Course deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }

        
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void btnEnrolledStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrolledStudentActionPerformed
        // TODO add your handling code here:
        Professor p = this.business.getProfessorDirectory().findByUserName(useraccount.getUsername());
        new EnrolledStudent(business, useraccount, p);
        
    }//GEN-LAST:event_btnEnrolledStudentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new MainJFrame(this.business, this.useraccount);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedbackActionPerformed
        // TODO add your handling code here:
         Professor professor = this.business.getProfessorDirectory().findByUserName(useraccount.getUsername());
         FeedbackWindow feedbackWindow = new FeedbackWindow(business,useraccount,professor);
         this.setVisible(false);
        
    }//GEN-LAST:event_btnFeedbackActionPerformed

    private void txtSubscriptionFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubscriptionFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubscriptionFeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnEnrolledStudent;
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPaySubscription;
    private javax.swing.JButton btnUpdateCourse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCourseOffered;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblReputationIndex;
    private javax.swing.JLabel lblSubscription;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable profCourseTable;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtReputationIndex;
    private javax.swing.JTextField txtSubscriptionFee;
    // End of variables declaration//GEN-END:variables
}
