/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Main.WorkSpaceProfiles.OrderManagement;

import MarketAnalytics.AnalysisHelper;
import TheBusiness.Business.Business;
import TheBusiness.MarketModel.Market;
import TheBusiness.MarketModel.SolutionOffer;
import TheBusiness.ProductManagement.Product;
import TheBusiness.SalesManagement.SalesPersonProfile;
import TheBusiness.Supplier.Supplier;
import UserInterface.Main.WorkSpaceProfiles.SalesPersonWorkAreaJPanel;
import java.awt.Color;
import java.awt.Font;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

        
/**
 *
 * @author renuka
 */
public class PerformanceReportsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PerformanceReportsJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Supplier selectedsupplier;
    Product selectedproduct;
    AnalysisHelper helper;
    SalesPersonProfile salesperson;



    public PerformanceReportsJPanel(Business bz, JPanel jp,AnalysisHelper helper,SalesPersonProfile salesperson) {
        CardSequencePanel = jp;
        this.business = bz;
        this.helper = helper;
        this.salesperson = salesperson;
        initComponents();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTopSolutions = new javax.swing.JButton();
        btnTopCustomers = new javax.swing.JButton();
        btnTopSalesPerson = new javax.swing.JButton();
        btnMarginalRevenue = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Performance Report - Sales");

        btnTopSolutions.setText("Top solutions");
        btnTopSolutions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopSolutionsActionPerformed(evt);
            }
        });

        btnTopCustomers.setText("Top customers");
        btnTopCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopCustomersActionPerformed(evt);
            }
        });

        btnTopSalesPerson.setText("Top sales people");
        btnTopSalesPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopSalesPersonActionPerformed(evt);
            }
        });

        btnMarginalRevenue.setText("Marginal revenue");
        btnMarginalRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarginalRevenueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnMarginalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTopSolutions, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTopCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTopSalesPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(221, 221, 221))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(385, 385, 385))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(99, 99, 99)
                .addComponent(btnTopSolutions)
                .addGap(32, 32, 32)
                .addComponent(btnTopCustomers)
                .addGap(37, 37, 37)
                .addComponent(btnTopSalesPerson)
                .addGap(30, 30, 30)
                .addComponent(btnMarginalRevenue)
                .addGap(68, 68, 68)
                .addComponent(btnBack)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    SalesPersonWorkAreaJPanel salesPersonWorkAreaPanel = new SalesPersonWorkAreaJPanel(business,salesperson, CardSequencePanel);
    // Remove the current panel and show the previous panel
    CardSequencePanel.removeAll();
    CardSequencePanel.add("SalesPersonWorkArea", salesPersonWorkAreaPanel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTopSolutionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopSolutionsActionPerformed
     CategoryDataset dataset = createSalesDataset();

    // Create chart based on the dataset
    JFreeChart chart = ChartFactory.createBarChart(
            "Top 3 Best Sales People",     // Chart title
            "Sales",             // X-axis label
            "Number of orders sold above target price",    // Y-axis label
            dataset);
    customizeBarChart(chart);

    // Display the chart in a frame
    ChartFrame frame = new ChartFrame("Results", chart);
    frame.pack();
    frame.setVisible(true);
    }//GEN-LAST:event_btnTopSolutionsActionPerformed

    private void btnTopCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopCustomersActionPerformed
        // TODO add your handling code here:
         CategoryDataset dataset = createCustomersDataset();

        //Create chart based on the dataset
        JFreeChart chart = ChartFactory.createBarChart(
                "Top 3 best customers",     // Chart title
                "Customers",             // X-axis label
                "Number of orders bought above target price",    // Y-axis label
                dataset);
        customizeBarChart(chart);
        
        ChartFrame frame = new ChartFrame("Results", chart);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_btnTopCustomersActionPerformed

    private void btnTopSalesPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopSalesPersonActionPerformed
        // TODO add your handling code here:
        CategoryDataset dataset = createSalesDataset();

     // Create chart based on the dataset
     JFreeChart chart = ChartFactory.createBarChart(
             "Top 3 Best Sales People",     // Chart title
             "Sales",             // X-axis label
             "Number of orders sold above target price",    // Y-axis label
             dataset);

     // Display the chart in a frame
     ChartFrame frame = new ChartFrame("Results", chart);
     frame.pack();
     frame.setVisible(true);
    }//GEN-LAST:event_btnTopSalesPersonActionPerformed

    private void btnMarginalRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarginalRevenueActionPerformed
        // TODO add your handling code here:
         CategoryDataset dataset = createMarginDataset();

        // Create chart based on the dataset
        JFreeChart chart = ChartFactory.createBarChart(
                "Total marginal revenue broken down by market",     // Chart title
                "Market",             // X-axis label
                "Margin over the orders based on Marktet",    // Y-axis label
                dataset);
        customizeBarChart(chart);
        
        ChartFrame frame = new ChartFrame("Results", chart);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_btnMarginalRevenueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMarginalRevenue;
    private javax.swing.JButton btnTopCustomers;
    private javax.swing.JButton btnTopSalesPerson;
    private javax.swing.JButton btnTopSolutions;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

private PieDataset createNegotiatedSolutionsDataset() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        HashMap<SolutionOffer, Integer> best_solution_offers = helper.getBestSolutionOffers(business, false);
        List<Map.Entry<SolutionOffer, Integer>> sortedEntries = helper.sortSolutionOffersByMargin(best_solution_offers);
        
        int topCount = 3;
        for (int i = sortedEntries.size() - 1; i >= 0 && topCount > 0; i--, topCount--) {
            Map.Entry<SolutionOffer, Integer> entry = sortedEntries.get(i);
            SolutionOffer s = entry.getKey();
            int value = entry.getValue();
            // Add data to the dataset
            dataset.setValue(s.getMarketchannelcomb().getMarket().getName()+"_"+s.getMarketchannelcomb().getChannel().getChannelType()+"_"+s.getProduct().getName(), value);
            // System.out.println("Market: "+s.getMarketchannelcomb().getMarket().getName() + "\tChannel: "+ s.getMarketchannelcomb().getChannel().getChannelType() + "\tSolution_price: " + s.getPrice() + "\tProduct_name: " + s.getProduct().getName() + "\tMargin: "+value);
        }

        return (PieDataset) dataset;
    }
    
    private CategoryDataset createCustomersDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    HashMap<String, Integer> best_customers = helper.getBestCustomers(business, false);
        // Sort the HashMap by values
        List<Map.Entry<String, Integer>> sortedEntries = helper.sortByValues(best_customers);

        // Display the sorted entries
        int topCount = 3;
        for (int i = sortedEntries.size() - 1; i >= 0 && topCount > 0; i--, topCount--) {
            Map.Entry<String, Integer> entry = sortedEntries.get(i);
            String customer_name = entry.getKey();
            int value = entry.getValue();
            dataset.addValue(value, "Best Customer", customer_name);
        }
        
        return (CategoryDataset) dataset;
    }
    
    private CategoryDataset createSalesDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        HashMap<String, Integer> best_sales_people = helper.getBestSalesPeople(business, false);
        // Sort the HashMap by values
        List<Map.Entry<String, Integer>> sortedEntries = helper.sortByValues(best_sales_people);

        // Display the sorted entries
        int topCount = 3;
        for (int i = sortedEntries.size() - 1; i >= 0 && topCount > 0; i--, topCount--) {
            Map.Entry<String, Integer> entry = sortedEntries.get(i);
            String customer_name = entry.getKey();
            int value = entry.getValue();
            dataset.addValue(value, "Best Sales Person", customer_name);
        }
        
        return (CategoryDataset) dataset;
    }
    
    public JFreeChart createChart( PieDataset dataset, String heading ) {
      JFreeChart chart = ChartFactory.createPieChart(
         heading,   // chart title 
         dataset,          // data ChartFactory   
         true,             // include legend   
         true, 
         false);

      return chart;
    }

    private void customizeBarChart(JFreeChart chart) {
        // Bar chart styling
        chart.setBackgroundPaint(Color.white);
        CategoryPlot plot = chart.getCategoryPlot();
        CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45); // Rotate labels for better readability
        domainAxis.setTickLabelFont(new Font("SansSerif", Font.PLAIN, 12));
        chart.getLegend().setItemFont(new Font("SansSerif", Font.PLAIN, 12));
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        // Set maximum bar width in data units
        renderer.setMaximumBarWidth(0.1);
    }
    
    private CategoryDataset createMarginDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        HashMap<Market, Integer> margin_by_market = helper.totalMarginalRevenueByMarket(business, false);
        Iterator<Map.Entry<Market, Integer>> iterator = margin_by_market.entrySet().iterator();
        while (iterator.hasNext()) {
            Map.Entry<Market, Integer> entry = iterator.next();
            Market m = entry.getKey();
            int value = entry.getValue();
            dataset.addValue(value, "Market_Margin", m.getName());
        }
        
        return (CategoryDataset) dataset;
    }
        

}
