/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Insurance;

/**
 *
 * @author srivarinimandali
 */
public class InsuranceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceJPanel
     */
    Insurance insurance;
    public InsuranceJPanel(Insurance insurance) {
        initComponents();
        this.insurance=insurance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCorporateId = new javax.swing.JLabel();
        txtCorporateId = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPremium = new javax.swing.JLabel();
        txtPremium = new javax.swing.JTextField();
        lblDeductable = new javax.swing.JLabel();
        txtDeductable = new javax.swing.JTextField();
        lblBenefits = new javax.swing.JLabel();
        scrollPaneBenefits = new javax.swing.JScrollPane();
        txtBenefits = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(199, 218, 211));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("INSURANCE");

        lblCorporateId.setText("Corporate ID :");

        txtCorporateId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorporateIdActionPerformed(evt);
            }
        });

        lblAddress.setText("Address :");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        lblPremium.setText("Premium :");

        txtPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPremiumActionPerformed(evt);
            }
        });

        lblDeductable.setText("Deductable :");

        txtDeductable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeductableActionPerformed(evt);
            }
        });

        lblBenefits.setText("Benefits :");

        txtBenefits.setColumns(20);
        txtBenefits.setRows(5);
        scrollPaneBenefits.setViewportView(txtBenefits);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAddress)
                            .addComponent(lblCorporateId)
                            .addComponent(lblPremium)
                            .addComponent(lblDeductable)
                            .addComponent(lblBenefits))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorporateId, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPaneBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnSave)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorporateId)
                    .addComponent(txtCorporateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPremium)
                    .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeductable)
                    .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBenefits)
                    .addComponent(scrollPaneBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorporateIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorporateIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorporateIdActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPremiumActionPerformed

    private void txtDeductableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeductableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeductableActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        insurance.setAddress(txtAddress.getText());
        insurance.setBenefits(txtBenefits.getText());
        insurance.setCorporateId(txtCorporateId.getText());
        insurance.setDeductable(txtDeductable.getText());
        insurance.setPremium(txtPremium.getText());
        JOptionPane.showMessageDialog(this,"Insurance Information Saved.");        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblCorporateId;
    private javax.swing.JLabel lblDeductable;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollPaneBenefits;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextArea txtBenefits;
    private javax.swing.JTextField txtCorporateId;
    private javax.swing.JTextField txtDeductable;
    private javax.swing.JTextField txtPremium;
    // End of variables declaration//GEN-END:variables
}
