/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.SystemAdmin;

import Business.Business;
import Business.UserAccount;
import UI.main.MainJFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 18572
 */
public class AddCourseJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddCourseJFrame
     */
     private Business business;
   
    private UserAccount useraccount;
    public AddCourseJFrame() {
        initComponents();
    }

     public AddCourseJFrame(Business business,UserAccount useraccount) {
        initComponents();
         this.setVisible(true);
        this.business = business;
        this.useraccount = useraccount;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDuration = new javax.swing.JTextField();
        txtCredits = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblAddCourse1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblId1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblCredits1 = new javax.swing.JLabel();
        lblDuration1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtDuration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtCredits.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnAdd.setFont(new java.awt.Font("American Typewriter", 1, 28)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(30, 76, 216));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("American Typewriter", 1, 28)); // NOI18N
        btnBack.setForeground(new java.awt.Color(30, 76, 216));
        btnBack.setText("<< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("American Typewriter", 1, 28)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(30, 76, 216));
        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblAddCourse1.setBackground(new java.awt.Color(241, 241, 241));
        lblAddCourse1.setFont(new java.awt.Font("American Typewriter", 1, 32)); // NOI18N
        lblAddCourse1.setForeground(new java.awt.Color(32, 78, 216));
        lblAddCourse1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddCourse1.setText("ADD COURSES");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.png"))); // NOI18N

        lblId1.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblId1.setForeground(new java.awt.Color(32, 78, 216));
        lblId1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId1.setText("ID :");

        lblName1.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblName1.setForeground(new java.awt.Color(32, 78, 216));
        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName1.setText("Name :");

        lblCredits1.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblCredits1.setForeground(new java.awt.Color(32, 78, 216));
        lblCredits1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCredits1.setText("Credits :");

        lblDuration1.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblDuration1.setForeground(new java.awt.Color(32, 78, 216));
        lblDuration1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDuration1.setText("Duration :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddCourse1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(103, 103, 103))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblId1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCredits1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                    .addComponent(lblDuration1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addComponent(txtCredits)
                    .addComponent(txtDuration))
                .addGap(0, 197, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblAddCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCredits1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCredits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuration1)
                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnBack))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    String id = txtId.getText();
    String name = txtName.getText();
    String creditsText = txtCredits.getText();
    String duration = txtDuration.getText();

    // Check for empty fields
    if (id.isEmpty() || name.isEmpty() || creditsText.isEmpty() || duration.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
        return; // Exit the method.
    }

    int credits;
    try {
        credits = Integer.parseInt(creditsText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Credits must be a valid number.");
        return; // Exit the method.
    }

    // Additional custom validations
    if (!isValidCourseId(id)) {
        JOptionPane.showMessageDialog(null, "Course ID must follow a specific format.");
        return; // Exit the method.
    }

    if (!isValidCourseName(name)) {
        JOptionPane.showMessageDialog(null, "Course name is not valid.");
        return; // Exit the method.
    }

    if (!isValidCourseDuration(duration)) {
        JOptionPane.showMessageDialog(null, "Course duration is not valid.");
        return; // Exit the method.
    }

    // Check if a course with the same ID already exists
    if (courseExists(id)) {
        JOptionPane.showMessageDialog(null, "A course with the same ID already exists.");
        return; // Exit the method.
    }

    // If all validations pass, add the course
    this.business.getGlobalCourseDir().addCourse(id, name, credits, duration);
    JOptionPane.showMessageDialog(null, "Course Added Successfully");
}

// Implement the 'isValidCourseId' method to check if the course ID follows a specific format
private boolean isValidCourseId(String courseId) {
    // Define the logic to check if the course ID follows a specific format
    // Return true if it's valid, false if it's not
    // Example: return courseId.matches("^[A-Z]{2}-\\d{4}$"); // Assuming a format like "AB-1234"
return courseId.matches("^[A-Z]{2}-\\d{4}$");
}

// Implement the 'isValidCourseName' method to check if the course name is valid
private boolean isValidCourseName(String courseName) {
    // Define the logic to check if the course name is valid
    // Return true if it's valid, false if it's not
    // Example: return courseName.matches("^[A-Za-z\\s]{3,50}$"); // Assuming 3-50 characters
        return courseName.matches("^[A-Za-z\\s]{3,50}$");
 // Replace with your actual logic
}

// Implement the 'isValidCourseDuration' method to check if the course duration is valid
private boolean isValidCourseDuration(String courseDuration) {
    // Define the logic to check if the course duration is valid
    // Return true if it's valid, false if it's not
    // Example: return courseDuration.matches("^\\d+\\s*(years|months|days)$"); // Assuming format like "4 years"
   return courseDuration.matches("^\\d+\\s*(years|months|days)$");// Replace with your actual logic
}

// Implement the 'courseExists' method to check if a course with the same ID already exists
private boolean courseExists(String courseId) {
    // Define the logic to check if a course with the same ID already exists
    // Return true if it exists, false if it does not
    // Example: return this.business.getGlobalCourseDir().courseExists(courseId);
    return false; // Replace with your actual logic


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new CourseCatalogJFrame(business, useraccount) ;
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new MainJFrame(this.business,this.useraccount) ;
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCourseJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddCourse1;
    private javax.swing.JLabel lblCredits1;
    private javax.swing.JLabel lblDuration1;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
