/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.SystemAdmin;

import Business.Business;
import Business.UserAccount;
import UI.main.MainJFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author renuka
 */
public class SystemAdminLoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminLoginJFrame
     */
    Business business;
    UserAccount useraccount;
    public SystemAdminLoginJFrame() {
        initComponents();
    }
    public SystemAdminLoginJFrame(Business business,UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.useraccount = useraccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        adminUsername_txt = new javax.swing.JTextField();
        lblManuYear = new javax.swing.JLabel();
        loginAdminBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        adminPassword_txt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 76, 216));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN LOGIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 50, 800, 40));

        lblModel.setFont(new java.awt.Font("Baskerville", 1, 24)); // NOI18N
        lblModel.setForeground(new java.awt.Color(30, 76, 216));
        lblModel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModel.setText("Username :");
        jPanel1.add(lblModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));
        jPanel1.add(adminUsername_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 240, 30));

        lblManuYear.setFont(new java.awt.Font("Baskerville", 1, 24)); // NOI18N
        lblManuYear.setForeground(new java.awt.Color(30, 76, 216));
        lblManuYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManuYear.setText("Password :");
        jPanel1.add(lblManuYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 130, -1));

        loginAdminBtn.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        loginAdminBtn.setForeground(new java.awt.Color(30, 76, 216));
        loginAdminBtn.setText("LOGIN");
        loginAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAdminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 110, 40));

        jButton1.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(30, 76, 216));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 100, 40));

        adminPassword_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPassword_txtActionPerformed(evt);
            }
        });
        jPanel1.add(adminPassword_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 240, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vector-distance-learning-concept-isolated-white-background-179184506.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAdminBtnActionPerformed
        // TODO add your handling code here:
                String username = adminUsername_txt.getText() ;              
              char[] passwordChars = adminPassword_txt.getPassword(); // Retrieve the entered password
              String password = new String(passwordChars); 
        if(this.business.getCommonUserAccountDirectory().authenticateUser(username, password) != null) {
            UserAccount user = this.business.getCommonUserAccountDirectory().authenticateUser(username, password);
           
           
              new SystemAdminJFrame(business, user);
            this.setVisible(false);
        } 
        else{
            JOptionPane.showMessageDialog(null, "Incorrect username or password. Please try again.");
        }    
        adminPassword_txt.setText("");
        adminUsername_txt.setText("");
       
    }//GEN-LAST:event_loginAdminBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MainJFrame(this.business,this.useraccount) ;
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adminPassword_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPassword_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPassword_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdminLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdminLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdminLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdminLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemAdminLoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adminPassword_txt;
    private javax.swing.JTextField adminUsername_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblManuYear;
    private javax.swing.JLabel lblModel;
    private javax.swing.JButton loginAdminBtn;
    // End of variables declaration//GEN-END:variables
}
